name: Android CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create local.properties
        run: |
          echo "Creating local.properties file"
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" > local.properties
          echo "signing.password=${{ secrets.SIGNING_PASSWORD }}" >> local.properties
          echo "signing.secretKeyRingFile=${{ secrets.SIGNING_KEY_RING }}" >> local.properties
          echo "ossrhUsername=${{ secrets.OSSRH_USERNAME }}" >> local.properties
          echo "ossrhPassword=${{ secrets.OSSRH_PASSWORD }}" >> local.properties

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug

      - name: Check Kotlin code style
        run: ./gradlew ktlint

      - name: Check project's public API
        run: ./gradlew apiCheck

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: Sample App (Debug)
          path: ./app/build/outputs/apk/debug/app-debug.apk